### ISSUE TITLE
How to include MR,MF in Simbet.

### ISSUE THREAD

**Issue by mohit03031999** [npapanik/Adyton#26]
How to include a parameter of MR, MF in SimBET.

**Comment by epapapet** [comment]
Dear mohit03031999,
you can find this information in the wiki, specifically in the "List of Protocol specific parameters" (https://github.com/npapanik/Adyton/wiki/List-of-Protocol-specific-parameters).

You need to use the -PROFILE option with a file the contains the options AggregationType and Density.
