### ISSUE TITLE
shell printf invalid number error

### ISSUE THREAD

**Issue by julianofischer** [npapanik/Adyton#5]
When importing the following traces, an invalid number error is raised.

Milan
MIT
Intel
Haggle
Infocom05

[-] Extracting original dataset.. [OK]
 Step 1: Removing external nodes.. [OK]
 Step 2: Searching for inactive nodes.. [OK]
 Step 3: Sorting file.. [OK]
 Step 4: Normalizing contact time - [OK]
 Step 5: Searching for self-contacts - [OK]
 Step 6: Searching for contact duplicates - [OK]
 Step 7: Calculating node arrival time in the experiment - ./process.sh: line 122: printf: 2.00: invalid number

**Comment by npapanik** [comment]
It seems like a locale problem. The script expects "." as decimal separator, but "," is provided. Adding the  following line (at the begging of the script) will do the trick. 

```
export LC_NUMERIC="en_US.UTF-8" 
```

I'm going to reproduce the bug and check the solution asap.
