### ISSUE TITLE
Windows installation error (using cygwin)

### ISSUE THREAD

**Issue by npapanik** [npapanik/Adyton#9]
Adyton fails to compile under windows (using cygwin). The message output is the following. 

``` shell
core/Results.cc: In member function ‘void Results::writeSimulationSettings()’:
core/Results.cc:117:34: error: ‘popen’ was not declared in this scope
  if((setFile = popen(command, "r")) == NULL)
                                  ^
core/Results.cc:133:19: error: ‘pclose’ was not declared in this scope
  if(pclose(setFile) == -1)
                   ^
make: *** [Makefile:39: core/Results.o] Error 1
```

We can fix this issue by either using an alternative compiler or by using another function instead of popen()/pclose(). I'm going to try the latter approach since popen() is not standard ISO C++.

**Comment by epapapet** [comment]
A workaround that seems to be working (with the old version of Results.cc) is to change -std=c++11 to -std=gnu++11 (second line of Makefile). After this change I was able to compile and use Adyton under Cygwin in Windows 10.
